$: # 兜底匹配所有分支，不被 glob 匹配的分支
  vscode:
    - docker:
        image: cnbcool/default-dev-env:latest
      services:
        - name: vscode
          options:
            keepAliveTimeout: 2h
        - docker
      stages:
        - name: install fnpack
          script: |
            cd /root
            curl -fsSL -o fnpack https://static2.fnnas.com/fnpack/fnpack-1.2.3-linux-amd64
            chmod +x fnpack
            mv fnpack /usr/local/bin/fnpack

  push:
    - imports: https://cnb.cool/magiccode1412/secret/-/blob/main/env.yml
      stages:
        - name: sync_to_github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/${GITHUB_USERNAME}/${CNB_REPO_NAME_LOWERCASE}.git
            auth_type: https
            username: "${GITHUB_USERNAME}"
            password: "${GITHUB_ACCESS_TOKEN}"
            force: true